services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gamestation_db
      POSTGRES_USER: gamestation_db_user
      POSTGRES_PASSWORD: 0uKPZxbYA1CLO3bTpNhtQy0a84QLDtQ0
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./Backend/Spring/demo
    container_name: backend-spring
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/gamestation_db
      SPRING_DATASOURCE_USERNAME: gamestation_db_user
      SPRING_DATASOURCE_PASSWORD: 0uKPZxbYA1CLO3bTpNhtQy0a84QLDtQ0

  frontend:
    build: ./Frontend/Gamestation
    container_name: frontend-angular
    depends_on:
      - backend
    ports:
      - "443:443"

volumes:
  pgdata:
    name: desarrollo_pg_data